# https://github.com/dorny/paths-filter
python:
  - "src/backend/**"
  - "src/backend/**.py"
  - "pyproject.toml"
  - "poetry.lock"
  - "**/python_test.yml"
components-changes:
  - "src/backend/base/langflow/components/**"
starter-projects-changes:
  - "src/backend/base/langflow/initial_setup/**"
frontend-tests:
  - "src/frontend/tests/**"
frontend:
  - "src/frontend/**"
  - "**/typescript_test.yml"
docs:
  - "docs/**"
